version: '3'

services:
  dailyupdates-ui:
    image: aaronjtan/dailyupdates-ui:latest
    restart: unless-stopped

  dailyupdates-server:
    image: aaronjtan/dailyupdates:latest
    restart: unless-stopped
    
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy_directives.conf:/etc/nginx/proxy_directives.conf

      - /etc/letsencrypt/:/etc/letsencrypt
    restart: unless-stopped